### PR TITLE
A few typos, grammar and formatting

### PR DESCRIPTION
**Pull request by chrislf**
I have corrected a number of small typos, grammar and formatting mistakes: I hope this will be useful and not too nit-picky. This document has been of great help to me over the years and if this is a helpful contribution I'm happy to submit it.

Wherever there was a grammatical fix that might have introduced semantic changes, and I was unsure of the semantics, I did not fix the grammar (semantic errors are worse than grammatical).

Please let me know if you would rather I squash my commits for pulling - thank you.

### CODE REVIEW

**Comment by chrislf** [comment]
Looks like a lot of this was already done. Just rebasing my branch now.

**Comment by chrislf** [comment]
Rebased and squashed now.

**Comment by sdiehl** [comment]
>  This document has been of great help to me over the years and if this is a helpful contribution I'm happy to submit it.

Wonderful. Thanks for the fixes and glad it was useful to you when learning. :slightly_smiling_face:

**Comment by chrislf** [comment]
You're welcome!

**Pull request merged**
