### PR TITLE
fix typos in tutorial.md

### PR DESCRIPTION
**Pull request by Kinokkory**
Fixed typos in tutorial.md.

### CODE REVIEW

**Comment by sdiehl** [comment]
Thanks a lot!

**Comment by Kinokkory** [comment]
It seems that tutorial.md on sdiehl:master is not updated. I don't know why but probably there is something wrong.
https://github.com/sdiehl/wiwinwlh/commits/master/tutorial.md

**Comment by sdiehl** [comment]
Everything that was in the diff for this pull request seems to be merged properly. Perhaps it's just outdated refs when you tried pulling? ``git fetch --all``

**Comment by Kinokkory** [comment]
Oops, I simply forgot to correct some of the "multiparamater" typos! I should have checked carefully. 

Checking the history of a specific file on line, *some of the* merge-a-pull-request commits are shown explicitly, and so I got confused.

Sorry, and thank you for your kindness.

**Pull request merged**
