### PR TITLE
Use a lighter and responsive styling

### PR DESCRIPTION
**Pull request by owickstrom**
This mostly removes stuff that was not used anymore, but also replaces styling with a lighter look and better (IMHO) responsiveness.

haskell-1

The sidebar folds away on smaller screens and becomes a top bar:

haskell-2

The top bar has a "Show Menu" button which activates the navigation as a fullscreen overlay which scrolls:

haskell-3

Any click on "Close Menu" or one of the links in the navigation closes the fullscreen overlay.

## Testing

I've so far tested this in the following device/browser combos, which works well enough:

* Latest Chrome on OSX
* Safari on OSX
* Chrome on Android
* Mobile Safari on iPad 3

The "Language Extensions" table makes the page overflow and have a scrolling in the X axis, for the whole page. Not much to do about with a wide table, unless one wraps the table in a scrolling <div>. That could prevent the whole document from being horizontally scrollable.

### CODE REVIEW

**Comment by owickstrom** [comment]
As we talked about on Twitter, please try building this and see if the indentation is off in source code blocks. My build might be incorrect, or I have messed something up (but I can't find it).

**Comment by sdiehl** [comment]
I love it, it will be live as soon as the CI finishes.

**Comment by owickstrom** [comment]
Nice! :)

**Comment by owickstrom** [comment]
Did you get correct indentation, btw?

**Comment by owickstrom** [comment]
It seems it's off in the deployed site now. :/

**Comment by sdiehl** [comment]
Hmm, I am noticing the indentation problem.

**Comment by owickstrom** [comment]
It was the `$body` variable. Use the new build and it should be fine. :)

**Comment by sdiehl** [comment]
Yup, that fixed it. :+1:

**Comment by owickstrom** [comment]
Great. I'm off to bed now, but ping me if there's anything else that needs fixing.

**Comment by sdiehl** [comment]
Lovely, thanks for the work.

**Pull request merged**
