### PR TITLE
Typos tutorial.md

### PR DESCRIPTION
**Pull request by ARPL-c-63h**
Don't know how this works exactly, so if there is a better way then just let me know.
Like: What is a good 'chunk size'? Pull request after each chapter/section?
[This commit/pull request is after 1 Basics.]

### CODE REVIEW

**Comment by sdiehl** [comment]
This is great, thanks so much for the fixes. I'll merge this shortly after I landed the `ci-fixes` branch. :slightly_smiling_face:

**Comment by ARPL-c-63h** [comment]
I left one question in the text. In this Python code:
`def powersOfTwo(n):
    power=n
    square_list=[1]
    for i in range (1,n+1):
        square_list.append(2 ** i)
    return square_list
print(powersOfTwo(15)`
Why is there "power = n" in there?

**Comment by sdiehl** [comment]
That line in Python is redundant, can be removed.

**Comment by ARPL-c-63h** [comment]
More next weekend (probably : )

**Comment by sdiehl** [comment]
> More next weekend (probably : )

Merged now, thanks for the copy editing help. :+1:

**Comment by ARPL-c-63h** [comment]
You're welcome. I'm just learning Haskell, so contributing code is still a long way off. This something I can do ... and it is also good to brush up on my English (2 languages in one go : )

**Pull request merged**
