### PR TITLE
tutorial: Patch up some grammar in section on lens.

### PR DESCRIPTION
**Pull request by MostAwesomeDude**
The actual content has some problems, but those are being tracked in
sdiehl/wiwinwlh#67.

I tried to salvage the meaning as much as possible, but some of these
sentences are a little complex. :c

I am told that dutch surnames like "Van Laarhoven" should have their first
letter capitalized when used to refer to a person by surname alone. I'm
neither Dutch nor a Dutch speaker, so perhaps this is wrong.

The only controversial thing here is that I swapped "polarizing" for
"staggering". An event or property cannot be "polarizing for some". A
polarizing event or property literally divides all observers into two camps,
the poles, with different (polar) opinions. If something is only partially
polarizing, then it is not polarizing.

### CODE REVIEW

**Comment by sdiehl** [comment]
Thanks!

**Comment by fumieval** [comment]
Capitalized "Van Laarhoven lens" looks unusual to me, because it is a derivative term (like "van der Waals force") but not expressing Van Laarhoven himself, I think.

**Comment by sdiehl** [comment]
Yeah, I guess it's a little ambiguous because it's a subtitle. I looked at some other places where ``van`` is used in the same context and it's usually written in lower case as well.

I think Twan (@twanvl) s on Github actually, so if he shows up and corrects it then I'll make the change. :-)

**Comment by twanvl** [comment]
The "van" should not be capitalized, except at the start of a sentence.

**Pull request merged**
